name = "jai-bhavani-bill-generator"
compatibility_date = "2026-01-14"

type = "javascript"

[site]
bucket = "./dist"  # this is where your Vite build outputs static files
entry-point = "workers-site"
